apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: eventstore
  namespace:
spec:
  type: eventstore.mongodb
  version: v1
  metadata:
    - name: host
      value: 192.168.65.5:27018,192.168.65.5:27019,192.168.65.5:27020
    - name: replica-set
      value: mongors
    - name: databaseName
      value: "example_dapr"
    - name: username
      value: "example"
    - name: password
      value: "123456"
