apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace:
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://rabbitmq:rabbitmq_15672@192.168.65.3:5672"
    - name: consumerID
      value: "ddd-example"
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: deliveryMode
      value: "0"
    - name: requeueInFailure
      value: "true"
    - name: prefetchCount
      value: "0"
    - name: reconnectWait
      value: "0"
    - name: concurrencyMode
      value: single