apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace:
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: 192.168.65.3:6379
    - name: redisPassword
      value: "123456"
    - name: actorStateStore
      value: "true"
