kind: Service
apiVersion: v1
metadata:
  name: dapr-ddd-demo-command-service
  namespace: 
  labels:
    app: dapr-ddd-demo-command-service
spec:
  type: NodePort
  selector:
    app: dapr-ddd-demo-command-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dapr-ddd-demo-command-service
  namespace: 
  labels:
    app: dapr-ddd-demo-command-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-ddd-demo-command-service
  template:
    metadata:
      labels:
        app: dapr-ddd-demo-command-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dapr-ddd-demo-command-service"
        dapr.io/app-port: "8080"
    spec:
      # hostNetwork: true
      containers:
        - name: dapr-ddd-demo-command-service
          image: <no value>
          ports:
          - containerPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dapr-ddd-demo-command-service-ingress
  namespace: 
spec:
  rules:
  - http:
      paths:
      - path: /darp-cmd
        pathType: Prefix
        backend:
          service:
            name: dapr-ddd-demo-command-service
            port:
              number: 8080