env-type: dev
dev:
  app:
    id: cmd-service
    http-port: 9010
    root-url: /api/v1.0
  dapr:
    host: localhost
    http-port: 9011
    grpc-port: 9012
    pubsubs:
      - "pubsub"
  log:
    level: debug
test:
  app:
    id: cmd-service
    http-port: 8080
    root-url: /api/v1.0
  dapr:
    host: 127.0.0.1
    http-port: 3500
    grpc-port: 50001
    pubsubs:
      - "pubsub"
  log:
    level: debug
prod:
  app:
    id: cmd-service
    http-port: 8080
    root-url: /api/v1.0
  dapr:
    host: 127.0.0.1
    http-port: 3500
    grpc-port: 50001
    pubsubs:
      - "pubsub"
  log:
    level: debug

