env: dev
envs:
  dev:
    app:
      id: dapr-ddd-demo-command-service
      httpPort: 9030
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      httpPort: 9031
      grpcPort: 9032
      pubsubs:
        - "pubsub"
    log:
      level: debug
  test:
    app:
      id: dapr-ddd-demo-command-service
      httpPort: 8080
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      #httpPort: 3500
      #grpc-port: 50001
      pubsubs:
        - "pubsub"
    log:
      level: debug
  prod:
    app:
      id: dapr-ddd-demo-command-service
      httpPort: 8080
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      #httpPort: 3500
      #grpc-port: 50001
      pubsubs:
        - "pubsub"
    log:
      level: debug
