env: dev
envs:
  dev:
    app:
      id: dapr-ddd-demo-query-service
      httpPort: 9037
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      httpPort: 9038
      grpcPort: 9039
      pubsubs:
        - "pubsub"
    log:
      level: debug
    mongo:
      default:
        host: 192.168.64.8:27018, 192.168.64.8:27019, 192.168.64.8:27020
        replicaSet: mongors
        dbname: dapr-ddd-demo-dev
        user: ddd
        pwd: 123456
        maxPoolSize: 20
    neo4j:
      default:
        host: <no value>
        port: <no value>
        user: <no value>
        pwd: <no value>
  test:
    app:
      id: dapr-ddd-demo-query-service
      httpPort: 8080
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      #httpPort: 3500
      #grpc-port: 50001
      pubsubs:
        - "pubsub"
    log:
      level: debug
    mongo:
      default:
        host: 192.168.64.8:27018, 192.168.64.8:27019, 192.168.64.8:27020
        replicaSet: mongors
        dbname: dapr-ddd-demo-test
        user: ddd
        pwd: 123456
        maxPoolSize: 20
    neo4j:
      default:
        host: <no value>
        port: <no value>
        user: <no value>
        pwd: <no value>
  prod:
    app:
      id: dapr-ddd-demo-query-service
      httpPort: 8080
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      pubsubs:
      - "pubsub"
    log:
      level: debug
    mongo:
      default:
        host: 192.168.64.8:27018, 192.168.64.8:27019, 192.168.64.8:27020
        replicaSet: mongors
        dbname: dapr-ddd-demo-prod
        user: ddd
        pwd: 123456
        maxPoolSize: 20
    neo4j:
      default:
        host: <no value>
        port: <no value>
        user: <no value>
        pwd: <no value>