env : dev
dev :
  app:
    id: query-example
    http-port: 9020
    root-url: /api/v1.0
  dapr:
    host: localhost
    http-port: 9021
    grpc-port: 9022
    pubsubs:
      - "pubsub"
  log:
    level: debug
  mongo:
    host: 192.168.64.8:27018, 192.168.64.8:27019, 192.168.64.8:27020
    replica-set: mongors
    dbname: query-example
    user: query-example
    pwd: 123456
    max-pool-size: 20