env: dev
envs:

  dev:
    app:
      id: example-query-service
      httpPort: 9017
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      httpPort: 9018
      grpcPort: 9019
      eventStores:
        eventstore1:
          pubsub: pubsub1
        eventstore2:
          pubsub: pubsub2
    log:
      level: debug
    mongo:
      default:
        host: 192.168.65.3:27018,192.168.65.3:27019,192.168.65.3:27020
        replicaSet: mongors
        dbname: dev_query_example
        user: example
        pwd: 123456
        maxPoolSize: 20

  test:
    app:
      id: example-query-service
      httpPort: 8080
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      #httpPort: 3500
      #grpc-port: 50001
      pubsubs:
        - "pubsub"
    log:
      level: debug
    mongo:
      default:
        host: 192.168.64.8:27018, 192.168.64.8:27019, 192.168.64.8:27020
        replicaSet: mongors
        dbname: test_query_example
        user: ddd
        pwd: 123456
        maxPoolSize: 20


  prod:
    app:
      id: example-query-service
      httpPort: 8080
      rootUrl: /api/v1.0
    dapr:
      host: localhost
      pubsubs:
      - "pubsub"
    log:
      level: debug
    mongo:
      default:
        host: 192.168.64.8:27018, 192.168.64.8:27019, 192.168.64.8:27020
        replicaSet: mongors
        dbname: prod_query_example
        user: ddd
        pwd: 123456
        maxPoolSize: 20
    neo4j:
      default:
        host: <no value>
        port: <no value>
        user: <no value>
        pwd: <no value>